spring:
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MSSQLServer
    username: sa
    password:
    hikari:
      pool-name: hikariCP
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh

github:
  oauth2:
    client-id: 7e93a0c92201f9166685
    client-secret: ed5b6147f00ec39109dcfaf5d34ef431f4fb53dc
    callback-url: http://localhost:8080/station-finder/authorization/callback
    token-get-url: https://github.com/login/oauth/access_token
    user-info-url: https://api.github.com/user

baidu:
  map-url: http://api.map.baidu.com/place/v2/search
  map-ak: YnGAe9P3U503u5S0SZhAGTjwCclv5xx8