spring:
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MSSQLServer
    username: sa
    password:
    hikari:
      pool-name: hikariCP
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ENC(WOky4RA4GEoCjrgGVh3dMic9/ED8QutLcatR0bMQgO3nc17+TeRP2z0TJIGAZ3A1z1STAMUSApGF5CMJPu2JIcJPX/2fdHjFu1l+bCLCtIu9rttHnMS9VM3OEccWVlq1RYgkDYnVrWMVPMDnKZp1GEmnVZuDL1y+rOMJ1/uc7OYJTk4cBRjGnXkj42PUjqSwLHfNlfBAzNy4gwSO2PKlVJJqDW0q8n/144KoTsmQUkzwqXsY9xQN/w==)
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh

github:
  oauth2:
    client-id: 7e93a0c92201f9166685
    client-secret: ENC(FSNKrnqXSCaVEyEexXdNjN4KlUw9IyN5wvbEnKuVA580rHmu3tyTMjMWrl5K1emMfca/CqrOCGs=)
    callback-url: http://localhost:8080/station-finder/authorization/callback
    token-get-url: https://github.com/login/oauth/access_token
    user-info-url: https://api.github.com/user

baidu:
  map-url: http://api.map.baidu.com/place/v2/search
  map-ak: ENC(6WWA4LR34kphrqLjDSuKtNR5wIxPLdlTFrybvRWqiaz3nvG5ozo79kY0J61/7oXT)